<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.hzwhzw</groupId>
        <artifactId>Interknot-Web</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <groupId>top.hzwhzw</groupId>
    <artifactId>IW-file-service</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>IW-file-service</name>
    <description>IW-file-service</description>

    <properties>
        <java.version>17</java.version>
    </properties>
    <dependencies>

        <!-- ============ OpenFeign 核心依赖 ============ -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
        <!-- ============ LoadBalancer 核心依赖 ============ -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>
        <!-- Spring Web -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>


        <!-- MyBatis -->
        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>3.0.3</version>
        </dependency>


        <!-- MySQL驱动 -->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <scope>runtime</scope>
        </dependency>


        <!-- Lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>


        <!-- Spring Boot测试 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>


        <!-- MyBatis测试 -->
        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter-test</artifactId>
            <version>3.0.3</version>
            <scope>test</scope>
        </dependency>

        <!-- Sentinel -->
        <dependency>

            <groupId>
                com.alibaba.cloud
            </groupId>

            <artifactId>
                spring-cloud-starter-alibaba-sentinel
            </artifactId>

        </dependency>

        <!-- Seata -->
        <dependency>

            <groupId>
                com.alibaba.cloud
            </groupId>

            <artifactId>
                spring-cloud-starter-alibaba-seata
            </artifactId>

        </dependency>

        <!-- RabbitMQ -->
        <dependency>

            <groupId>
                org.springframework.boot
            </groupId>

            <artifactId>
                spring-boot-starter-amqp
            </artifactId>

        </dependency>

        <!-- web -->
        <dependency>

            <groupId>
                org.springframework.boot
            </groupId>

            <artifactId>
                spring-boot-starter-web
            </artifactId>

        </dependency>


        <!-- nacos注册发现 -->

        <dependency>

            <groupId>
                com.alibaba.cloud
            </groupId>

            <artifactId>
                spring-cloud-starter-alibaba-nacos-discovery
            </artifactId>

        </dependency>


        <!-- nacos配置中心 -->

        <dependency>

            <groupId>
                com.alibaba.cloud
            </groupId>

            <artifactId>
                spring-cloud-starter-alibaba-nacos-config
            </artifactId>

        </dependency>

        <!-- mybatis-plus -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
        </dependency>

        <!-- ============ Bootstrap 核心依赖 ============ -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
    </dependencies>

</project>
